# Generated by Django 4.2.1 on 2023-05-04 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "datetime"]},
        ),
    ]
